acl:
  allow:
    - vlan:
        - 300
        - outer: 200
          inner:
            - 100
#            - 101
      rate: 1
    - src:
        addresses:
          - 192.168.0.2/32
          - 192.168.100.0/24
      dst:
        addresses: 192.168.0.202
        ports:
          number: 80
          proto: tcp
      rate: 1

  drop:
    - vlan:
        - 140
        - outer: 130
          inner:
            - 100
    - src:
        addresses:
          - fe80::/64
      dst:
        addresses:
          - fe80::c274:2bff:fefa:720c
        ports:
          number: any
          proto: icmp

logging:
  PacketDrop: true
  RateLimited: false
  ConntrackMiss: false
  BackendSelected: false
  SlowPath: false
  ServiceMatched: true
  VlanDetected: true
  PacketAllow: false
rate_limit:
  global:
    max_tokens: 65536
    refill_per_sec: 64000
  per_rule_multiplier: 256
monitoring:
  ringbuf_bytes: 16777216
  poll_interval_ms: 100
